language: node_js
node_js:
  - "6"
  - "6.0"
  - "6.1"

sudo: false

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - git-core
    packages:
      - git  # GIT_TERMINAL_PROMPT is available from Git 2.3

before_script:
  - vim --version
  - git --version

script:
  - npm run lint
  - npm test
