language: node_js
node_js:
  - "12.10"
  - "12"
  - "13.0"
  - "13"
  - "14.0"
  - "14"
  - "node"

sudo: false

addons:
  apt:
    sources:
      - git-core
    packages:
      - git  # GIT_TERMINAL_PROMPT is available from Git 2.3

before_install:
  - npm install -g codecov

before_script:
  - vim --version
  - git --version

script:
  - npm test

after_success:
  - npm run coverage
  - codecov

jobs:
  include:
    - name: Lint
      node_js: "node"
      addons: {}
      before_install: skip
      script:
        - npm run lint
      after_success: skip
    - stage: npm release
      if: tag IS present
      node_js: "node"
      cache: {}
      addons: {}
      before_install: skip
      install: skip
      before_script: skip
      script: skip
      after_success: true  # Don't skip: To trigger the deploy
      deploy:
        provider: npm
        email: thinca+npm@gmail.com
        api_key:
          secure: UjuyMj2EcrK34uyml4xrYtlt5/14AVLlwwrF5tujJXZaenoaD+5gGP1IZls9o+vldWr6SxatJ05c5b+LTNb5RH+7S72s5Yn/QNtff8bsT3ajHidQ3qgeWhmsNXsPb4p2z+9syKjiFZ303KtW7ykVb1UYssir7y9N63ZE5iLEsEgeIYsX0Rq1Wt4hs7kLmHhDsN2aVAsLloAGEBNyMO3AJVpBfRQ+YmSBPOtrgmKPGgaRROPTIvRDW+kka5EbU98CHApHYgaFuzLlyAVWA5INvWc3bi442ZeS+KePyiy6HEyuje7GI1VlgHGzp/lUCWhdJFo5pDlbaBvpOZurTF4uXPt6LtemUW9pA3xhDLz1NM7oiR6ZuID7fv4B053UiBS5rduxjyr1LSyNOho+tQSjOwZePVKYSkpAT7HuEs4EVRUDwc1OcnGOAZa6z6l86KDde0zte86BplIUTTUIXxXAdLHZQ67pg+iwBSunlrlTJFML+0cmrW8DXpPoj6ZLsDsuUeeTDHiJWl6UEzG/FnRCVpwCR0/X3HZss8hMwsVQIweN+mlYs16KUEy+JIllbRRa7T9cHZ4D6H3uwk1pNShuKQtHZpDJzb6KHvXhRjiLUvhFNwSE8vO7GpkaiA8gDE3qbkt1o256h7fyg65Rw10wEUauYsASgUS7BvSz4H6ZgLo=
        on:
          tags: true
